---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 21ad4dfb75f0cda911528cd085b9d2be53e8b3da
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: camel-boot-ws
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: org.example.wsdl
  name: camel-boot-ws
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: camel-boot-ws
    provider: fabric8
    group: org.example.wsdl
