---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 92b73f37b9cbf03be6e35fcc92235873d72fda82
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    app: camel-boot-ws
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: org.example.wsdl
  name: camel-boot-ws
spec:
  ports:
  - name: dynamid
    port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: camel-boot-ws
    provider: fabric8
    group: org.example.wsdl
